real_estate/urls.py
"""real_estate URL Configuration
"""

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import  housing_estate.views
import housing_estate.dropdown
urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$',housing_estate.views.index, name='index'),
    #********HOUSING ESTATES URLS ********
    url(r'^housing_estate/', include('housing_estate.urls', namespace='housing_estate', app_name='housing_estate')),

    url(r'^address_display/$',housing_estate.dropdown.list_addresses,name='address_display'),

    url(r'^search_home/(?P<housetype>[-\w]+)/(?P<bed_number>[-\w]+)/(?P<min_price>[-\w]+)/(?P<max_price>[-\w]+)/search_home/$','housing_estate.dropdown.get_home',name='search_home'),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

housing_estate/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import admin
from django.forms import Select
from django.contrib.admin.widgets import AdminTimeWidget
from django.utils.safestring import mark_safe
from django.forms.widgets import TextInput
from django.conf import settings


from .models import Address, Apartment, Compound, Hostel, HostelRoom, House, Owner, HouseSpecification


class AddressForm(forms.ModelForm):
        class Meta:
                model = Address
                fields = '__all__'

        def __init__(self, *args, **kwargs):
                super(AddressForm, self).__init__(*args, **kwargs)
                self.fields['HouseNo'].widget.attrs['class'] = 'form-control'
                self.fields['StreetName'].widget.attrs['class'] = 'form-control' 
                self.fields['position'].widget.attrs['class'] = 'form-control'
                
                
class ApartmentForm(forms.ModelForm):
        class Meta:
                model = Apartment
                fields = '__all__'
        def __init__(self, *args, **kwargs):
                super(ApartmentForm, self).__init__(*args, **kwargs)
                self.fields['ApartmentName'].widget.attrs['class'] = 'form-control'
                self.fields['NoOfRooms'].widget.attrs['class'] = 'form-control' 
                self.fields['ApartmentSize'].widget.attrs['class'] = 'form-control'
                self.fields['compound'].widget.attrs['class'] = 'form-control'
                self.fields['ApartmentPaymentMode'].widget.attrs['class'] = 'form-control' 
                self.fields['price'].widget.attrs['class'] = 'form-control'
                self.fields['picture'].widget.attrs['class'] = 'form-control'
                
                          
class CompoundForm(forms.ModelForm):
        class Meta:
                model = Compound
                fields = '__all__'
        def __init__(self, *args, **kwargs):
                super(CompoundForm, self).__init__(*args, **kwargs)
                self.fields['CompoundName'].widget.attrs['class'] = 'form-control'
                self.fields['NoOfUnits'].widget.attrs['class'] = 'form-control' 
                self.fields['owner'].widget.attrs['class'] = 'form-control'
                self.fields['address'].widget.attrs['class'] = 'form-control'
                self.fields['picture'].widget.attrs['class'] = 'form-control'
                
                

class HostelForm(forms.ModelForm):
        class Meta:
                model = Hostel
                fields = '__all__'
        def __init__(self, *args, **kwargs):
                super(HostelForm, self).__init__(*args, **kwargs)
                self.fields['HostelName'].widget.attrs['class'] = 'form-control'
                self.fields['NumOfRooms'].widget.attrs['class'] = 'form-control' 
                self.fields['address'].widget.attrs['class'] = 'form-control'
                self.fields['owner'].widget.attrs['class'] = 'form-control'
                self.fields['picture'].widget.attrs['class'] = 'form-control' 



class HostelRoomForm(forms.ModelForm):
        class Meta:
                model = HostelRoom
                fields = '__all__'
        def __init__(self, *args, **kwargs):
                super(HostelRoomForm, self).__init__(*args, **kwargs)
                self.fields['RoomNumber'].widget.attrs['class'] = 'form-control'
                self.fields['Price'].widget.attrs['class'] = 'form-control' 
                self.fields['RoomSize'].widget.attrs['class'] = 'form-control'
                self.fields['RoomPaymentMode'].widget.attrs['class'] = 'form-control'
                self.fields['hostel'].widget.attrs['class'] = 'form-control'
                self.fields['picture'].widget.attrs['class'] = 'form-control' 



class HouseForm(forms.ModelForm):
        class Meta:
                model = House
                fields = '__all__'
        def __init__(self, *args, **kwargs):
                super(HouseForm, self).__init__(*args, **kwargs)
                self.fields['HouseName'].widget.attrs['class'] = 'form-control'
                self.fields['NoOfRooms'].widget.attrs['class'] = 'form-control' 
                self.fields['HouseSize'].widget.attrs['class'] = 'form-control'
                self.fields['owner'].widget.attrs['class'] = 'form-control'
                self.fields['address'].widget.attrs['class'] = 'form-control'
                self.fields['price'].widget.attrs['class'] = 'form-control'
                self.fields['HousePaymentMode'].widget.attrs['class'] = 'form-control'
                self.fields['picture'].widget.attrs['class'] = 'form-control'
                
                

class OwnerForm(forms.ModelForm):
        class Meta:
                model = Owner
                fields = '__all__'
        def __init__(self, *args, **kwargs):
                super(OwnerForm, self).__init__(*args, **kwargs)
                self.fields['FirstName'].widget.attrs['class'] = 'form-control'
                self.fields['MiddleName'].widget.attrs['class'] = 'form-control' 
                self.fields['LastName'].widget.attrs['class'] = 'form-control'
                self.fields['Email'].widget.attrs['class'] = 'form-control'
                self.fields['Phone'].widget.attrs['class'] = 'form-control'




HOUSE_TYPE_CHOICES=(
        ('','Choose..'),
        ('House','House'),
        ('Apartment','Apartment'),
        ('Hostel','Hostel')
)

BEDS_CHOICES=(
        ('','Choose..'),
        (1,'1+'),
        (2,'2+'),
        (3,'3+'),
        (4,'4+'),
        (5,'5+'),
        (6,'6+')
)

MIN_PRICE_CHOICES_RANGE=(
        ('','Choose..'),
        (0,'0'),
        (30000,'30,000'),
        (50000,'50,000'),
        (70000,'70,000'),
        (100000,'100,000'),
        (150000,'150,000')
)

MAX_PRICE_CHOICES_RANGE=(
        ('','Choose..'),
        (30000,'30,000'),
        (50000,'50,000'),
        (70000,'70,000'),
        (100000,'100,000'),
        (150000,'150,000'),
        (250000,'250,000')
)

YEAR_BUILT_MIN=(
        ('','Choose..'),
        (1990,'1990'),
        (2000,'2000')
)

YEAR_BUILT_MAX=(
        ('','Choose..'),
        (2000,'2000'),
        (2017,'2017')

)

CHOICES=[
        ('HasGypsum','Gypsum'),
        ('HasAluminiumWindows','Aluminium Windows'),
        ('HasTiles','Tiles'),
        ('SelfContained','Self Contained'),
        ('HasElectricity','Electricity'),
        ('VanishedRoom','Vanished Room'),
        ('HasGypsum','Gypsum'),
        ('HasAluminiumWindows','Aluminium Windows')
        ]



class EstateForm(forms.Form):
        housetype =  forms.ChoiceField(choices = HOUSE_TYPE_CHOICES, widget=forms.Select(attrs={'class': 'form-control seleckpicker'}))
        beds =  forms.ChoiceField(choices = BEDS_CHOICES, widget=forms.Select(attrs={'class': 'form-control seleckpicker'}))
        min_price =  forms.ChoiceField(choices = MIN_PRICE_CHOICES_RANGE, widget=forms.Select(attrs={'class': 'form-control seleckpicker'}))
        max_price =  forms.ChoiceField(choices = MAX_PRICE_CHOICES_RANGE, widget=forms.Select(attrs={'class': 'form-control seleckpicker'}))
        
        #year_built_min =  forms.ChoiceField(choices = YEAR_BUILT_MIN, widget=forms.Select(attrs={'class': 'form-control seleckpicker'}))
        #year_built_max =  forms.ChoiceField(choices = YEAR_BUILT_MAX, widget=forms.Select(attrs={'class': 'form-control seleckpicker'}))
        #rooms = forms.ChoiceField(choices = BEDS_CHOICES, widget=forms.Select(attrs={'class': 'form-control seleckpicker'}))
        choices = forms.MultipleChoiceField(choices=CHOICES, widget=forms.CheckboxSelectMultiple())
'''
class HouseSpecificationForm(forms.ModelForm):
        class Meta:
                model = HouseSpecification
                fields = '__all__'
        def __init__(self, *args, **kwargs):
                super(OwnerForm, self).__init__(*args, **kwargs)
                self.fields['HasGypsum'].widget.attrs['class'] = 'form-control'
                self.fields['HasAluminiumWindows'].widget.attrs['class'] = 'form-control' 
                self.fields['HasTiles'].widget.attrs['class'] = 'form-control'
                self.fields['Rented'].widget.attrs['class'] = 'form-control'
                self.fields['SelfContained'].widget.attrs['class'] = 'form-control'
                self.fields['VanishedRoom'].widget.attrs['class'] = 'form-control'
                self.fields['HasElectricity'].widget.attrs['class'] = 'form-control' 

'''

templates/base.html
{% load i18n admin_static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
{% block title %}
    <title> </title>
{% endblock %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <!-- FormValidation CSS file -->
    <link href="{% static 'formvalidation/dist/css/formValidation.css' %}" rel="stylesheet">
    <!--Bootstrap Validator CSS-->
    <link href="{% static 'css/bootstrapValidator.min.css' %}" rel="stylesheet prefetch">
    
    <!---JQUERY CSS -->
    <link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet">

    <!--FONT AWESOME -->
    <link href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">
    
   <script src="{% static 'js/jquery-1.12.4.js' %}"></script>
   
   <!-- Leaflet CSS-->
    <link href="{% static 'leaflet/leaflet.css' %}" rel="stylesheet">
	<!-- Leaflet OSMGeocoderCSS-->
	<link href="{% static 'leaflet-control-osm-geocoder-master/Control.OSMGeocoder.css' %}" rel="stylesheet">
	<!-- Leaflet JS-->
	<script src="{% static 'leaflet/leaflet.js' %}"></script>
	<!-- Leaflet OSMGeocoder JS-->
    <script src="{% static 'leaflet-control-osm-geocoder-master/Control.OSMGeocoder.js' %}"></script>
	
	<!-- Custom styles for this template -->
	<link href="{% static 'css/dashboard.css' %}" rel="stylesheet">	
    {% endblock %}
     
  </head>
<body>
      {% block navbar %}
        {% include 'navbar.html' %}
      {% endblock %}

    <div class="container-fluid">
        <div class="row">
            {% block main_section %}

            {% endblock %}
        </div>
	</div>

            {% block footer %}
                <!-- Site footer -->
                <footer class="navbar-default navbar-fixed-bottom">
                    <div class="container-fluid">
                        <p class="text-muted" align='center' >Real estate &copy; 2017 copyright.</p>
                    </div>
                </footer>
            {% endblock %}



{% block javascripts %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
     <!--- JQUERY JS-->
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <!--<script src="{% static 'js/jquery.min.js' %}"></script>-->
    <!--- Bootstrap JS-->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- FormValidation plugin and the class supports validating Bootstrap form -->
    <script src="{% static 'formvalidation/dist/js/formValidation.min.js' %}"></script>
    <script src="{% static 'formvalidation/dist/js/framework/bootstrap.min.js' %}"></script>
    
    <!--intl-tel-input-->
    <!--<script src="{% static 'intl-tel-input-10.0.0/build/js/intlTelInput.min.js' %}"></script>-->
    
    <!-- bootstrapvalidator  supports validating Bootstrap form -->
    <script src="{% static 'js/bootstrapvalidator.min.js' %}"></script>
	<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    <!--- Myscript JS-->
    <script src="{% static 'js/script.js' %}"></script>
    <script>
            if (document.location.search.match(/type=embed/gi)) {
                window.parent.postMessage("resize", "*");
                }
    </script>
    
{% endblock %}

{% block extended_javascripts_code %}

{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main_section %}


    <div class="col-sm-3 col-md-4 sidebar">

	<form class="well form-horizontal" action=" " method="post"  id="estate_form">{% csrf_token %}

		  <div class="form-group">
					{{ estateform.housetype.errors }}
					<label for="housetype" class="col-md-4 control-label">Home Type:</label>
						<div class="col-md-4 selectContainer">
							  {{ estateform.housetype }}
						</div>
		  </div>
		  <!--
		  <div class="form-group" id='hostel_rooms'>
					{{ estateform.rooms.errors }}
					<label for="rooms" class="col-md-4 control-label">No of room(s):</label>
						<div class="col-md-4 selectContainer">
							  {{ estateform.rooms }}
						</div>
		  </div>
		  -->
		  <div class="form-group" id='apart_house_bed'>
					{{ estateform.beds.errors }}
					<label for="beds" class="col-md-4 control-label">No of Bed(s):</label>
						<div class="col-md-4 selectContainer">
							  {{ estateform.beds }}
						</div>
		  </div>



		  <div class="form-group">
					{{ estateform.price_range.errors }}
					<label for="price_range" class="col-md-4 control-label">Price range:</label>
						<div class="col-md-4 selectContainer">
							  {{ estateform.min_price }} -  {{ estateform.max_price }}
						</div>
		  </div>
		   <!--
		  <div class="form-group">
					{{ estateform.year_built.errors }}
					<label for="year_built" class="col-md-4 control-label">Built year:</label>
						<div class="col-md-4 selectContainer">
							  {{ estateform.year_built_min }} - {{ estateform.year_built_max }}
						</div>
		  </div>
		  -->
		  <div class="form-group">
					{{ estateform.choices.errors }}
					<label for="choices" class="col-md-4 control-label">Has:</label>
						<div class="col-md-4 selectContainer">
							  {{ estateform.choices }}
						</div>
		  </div>


	</form>
	</div>

	<div class="col-sm-9 col-sm-offset-3 col-md-8 col-md-offset-4 main">
		  <!--<h1 class="page-header">Morogoro Region</h1>-->
		  <div id="map" style="width: 1200px; height: 900px"></div>
	</div>

{% endblock %}


{% block extended_javascripts_code %}
<script type="text/javascript">

    var osmLink = '<a href="http://openstreetmap.org">OpenStreetMap</a>',
        worldlink ='<a href="http://www.esri.com/">Esri</a>',
        thunLink = '<a href="http://thunderforest.com/">Thunderforest</a>';

    var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        osmAttrib = '&copy; ' + osmLink + ' Contributors';

        worldurl = 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
        worldAttrib = '&copy; ' + worldlink + ' Contributors',

        landUrl = 'https://{s}.tile.thunderforest.com/landscape/{z}/{x}/{y}.png?apikey=4ed9713c99264649908e5e085daa379f',
        thunAttrib = '&copy; '+ thunLink +' Contributors & ';


    var osmMap = L.tileLayer(osmUrl, {attribution: osmAttrib});
        worldMap = L.tileLayer(worldurl, {attribution: osmAttrib}),
        landMap = L.tileLayer(landUrl, {attribution: thunAttrib});


    var map = L.map('map', {
        layers:[osmMap],
        center: [-6.8304, 37.6706],
                zoom:15,
                maxZoom: 17,
                minZoom:10,
                zoomControl: false,
                attributionControl: false
                });

    var baseLayers = {
        "Open Street Map":osmMap,
        "Satelite Map":worldMap,
        "Landscape Map":landMap

    };

    L.control.layers(baseLayers).addTo(map);

    var osmGeocoder = new L.Control.OSMGeocoder({
            collapsed: true,
            position: 'bottomright',
            text: 'Search Place!',
			});
       map.addControl(osmGeocoder);

	 /*var marker = L.marker([-6.8304, 37.6706],{
            opacity:1,
            title:'Hover Text'
            }).addTo(map)
                .bindPopup('<b>Te Papa</b><br>My popup.');

	  */

</script>
<script>
/*
$(document).ready(function() {
	  $('#id_housetype').change(function() {
			if ($(this).val() =='' ) {
                $('#hostel_rooms').hide();
				$('#apart_house_bed').hide();
            }
			else if ($(this).val() =='Hostel'){
			    $('#hostel_rooms').show();
				$('#apart_house_bed').hide();
				$('#id_beds').val(-999);
            }
			else if ($(this).val() =='Apartment' || $(this).val() == 'House') {
				$('#hostel_rooms').hide();
				$('#id_rooms').val(-999);
				$('#apart_house_bed').show();

			}

	  })


});
*/
</script>
<script>
$(document).ready(function() {
		  $("#id_housetype,#id_beds,#id_min_price,#id_max_price").on('propertychange change click keyup input', function () {

        alert($('#id_max_price').val());
        /*
			if ($('#id_min_price').val() == '') {
                $('#id_min_price').val(90);
            }
			if ($('#id_max_price').val() == '') {
                $('#id_max_price').val(90);
            }
			if ($('#id_beds').val() == '') {
                $('#id_beds').val(90);
            }
			if ($('#id_housetype').val() == '') {
                $('#id_housetype').val('ALL');
            }
          */
			var url = "/search_home/" + $('#id_housetype').val() + '/' + $('#id_beds').val() + '/' +  $('#id_min_price').val() + '/' + $('#id_max_price').val() +  "/search_home";
				  $.getJSON(url, function(home_instance) {

            for (var i = 0; i < home_instance.length; i++) {
              var coordinate = retrieved_address[i].fields['hostel'].split(',')
              console.log(coordinate);
            }

					})
        })
});
</script>

<script>
$(window).load(function() {
	  var url = "/address_display/";
	  $.getJSON(url, function(retrieved_address) {
			for (i=0; i < retrieved_address.length; i++ ) {
				  var coordinate = retrieved_address[i].fields['position'].split(',')
				  var 	latitude = coordinate[0],longitude = coordinate[1];
                marker = new L.marker([latitude,longitude]).addTo(map).bindPopup(retrieved_address[i].pk);
            }


	  })


});
</script>



<script>
   $(document).on('submit','#id_form',function(e){
     e.preventDefault();
     $.ajax({
             type:'POST',
             url:'/let_test/',
             data: $("form").serialize(),
             cache: false,
             success: function (data, status) {
                 if (data['stat'] == "error") {
                  $("#id_general_error").show();

                 }
                 else {
                  if (data['irrigation_type'] == 'SPK') {
                   if (data['irrigation_category'] == 'SSS') {
                   window.location.href='/sprinkler/solid_set/'+data['crop_name']+'/'+data['max_app_rate']+'/'+data['irrigation_interval_per_days']+'/'+data['ET_maximum']+'/'+data['soil_id']+'/'+data['latitude']+'/'+data['longitude']+'/'+data['rainfall_category'];//+'/'+data['planting_date'];
                   }
                   else if (data['irrigation_category'] == 'HMS') {
                   window.location.href='/sprinkler/drag_hose/'+data['crop_name']+'/'+data['max_app_rate']+'/'+data['irrigation_interval_per_days']+'/'+data['ET_maximum']+'/'+data['soil_id']+'/'+data['latitude']+'/'+data['longitude'];
                   }
                   else if (data['irrigation_category'] == 'TG') {
                   window.location.href='/travelling_gun/travel_gun/'+data['crop_name']+'/'+data['max_app_rate']+'/'+data['irrigation_interval_per_days']+'/'+data['ET_maximum']+'/'+data['soil_id']+'/'+data['latitude']+'/'+data['longitude']+'/'+data['rainfall_category']+'/'+data['RAW'];
                   }
                  }
                  else if (data['irrigation_type'] == 'DRP') {
                   window.location.href='/microirrigation/trickle/'+data['crop_name']+'/'+data['soil_id']+'/'+data['ET_maximum']+'/'+data['latitude']+'/'+data['longitude']+'/'+data['category']+'/'+data['plant_spacing']+'/'+data['plant_row_spacing'];
                  }
                  else if (data['irrigation_type'] == 'SUR') {
                  window.location.href='/furrow/'+data['crop_name']+'/'+data['max_app_rate']+'/'+data['irrigation_interval_per_days']+'/'+data['ET_maximum']+'/'+data['category'];
               }

                 }
             }
         });
  return false;
   });

</script>
{% endblock %}